// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with fallback to hardcoded values for production
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://jimfuknlntcqgtqfwcod.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppbWZ1a25sbnRjcWd0cWZ3Y29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMjAyNDksImV4cCI6MjA3NzY5NjI0OX0.Flky3o6WN5t1g2emMO84mWiyQWnHqzpLoW2MgGl8wYA';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);